<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>StrafeClient</AssemblyName>
    <RootNamespace>StrafeClient</RootNamespace>
    <Product>Strafe Client</Product>
    <Company>Strafe Client</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageReference Include="XboxAuthNet" Version="3.0.5" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
